### ISSUE TITLE
Where da Download at?

### ISSUE THREAD

**Issue by Ralphy2405** [TeamBR-Modding/Lux-et-Umbra-Redux#2]
Hey BRModding Team,

I just wanted to ask where the download for the mod was since i cant seem to find it. It would be great if this mod could make its way to either its own website or to minecraft Curseforge.

Yours
Ralphy2405

**Comment by pauljoda** [comment]
Perhaps I should have made this more clear earlier. This version of the mod is the version that we are making from scratch. The version we wrote for the Modding Trials is available here http://teambrmodding.com:8080/job/Lux%20et%20Umbra%20-%201.10.2/

We are starting over with the same idea, but a different approach. That version of the mod will no longer be worked on. We removed all the code and started this one. At the moment, the version only has a book that opens an image. I'm currently working on the backend of the book to enable us to document the mod easily as we develop. 

I would expect to see some content out of this version within the month of so. When we feel we are at a point where we feel we can release, we will announce and put it on Curse. 

Sorry about the confusion. Glad you are interested in the mod. This new version (the real mod) will be much better and I think people will really like where we are heading. Please have patience as we work towards that goal. It is difficult to mod around busy work days and other life events.
